services:

  lakehouse:

    build: .

    container_name: euromillions-lakehouse

    volumes:
      - .:/app
      - C:\Users\pdcge\.dbt:/root/.dbt

    working_dir: /app

    stdin_open: true

    tty: true

    ports:
      - "8080:8080"