version: 2

models:
  - name: silver_draws

    description: >
      Canonical cleaned EuroMillions draw dataset.

    columns:

      - name: draw_id

        description: Unique identifier for each draw.

        tests:
          - not_null
          - unique

      - name: draw_date

        description: Official draw date.

        tests:
          - not_null

      - name: jackpot_amount

        description: Total jackpot amount in EUR.

        tests:
          - not_null